openapi: 3.0.3
info:
  title: DEMO
  description: OpenAPI Demo
  version: v1
paths:
  /jobs:
    summary: Jobs
    get:
      summary: List all jobs
      x-grpc-endpoint: growing.graphql.example.JobService/List
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    name:
                      type: string
                    description:
                      type: string
  /jobs/{jobId}:
    summary: Get Job
    get:
      summary: Get job by id
      x-grpc-endpoint: growing.graphql.example.JobService/Get
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  description:
                    type: string
