openapi: 3.1.0
info:
  title: 测试项目
  description: 测试项目
  version: v1
paths:
  /getJobs:
    get:
      summary: io.growing.gateway.example.JobService
      description: 获取所有Jobs.
      parameters:
        - name: accessToken
          in: query
          allowEmptyValue: false
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
        "404":
          description: "not found"
        "405":
          description: "method not supported"




