openapi: 3.1.0
info:
  title: 测试项目
  description: 测试项目
  version: v1
paths:
  /getJobs:
    get:
      summary: 获取所有Jobs
      description: 获取所有Jobs.
    parameters:
      -name: accessToken
        in: query
    responses:
      "200":
        description: "success"
        content:
          application/json:
            schema: object
      "404":
        "not found"
      "405":
        "method not supported"
  /createJob:
    put:
      summary: 创建jobs
      description: 创建jobs.
    requestBody:
      reqired: true
      content:
        application/json:
          schema:
            type: string
    responses:
      "200":
        description: "success"
        content:
          application/json:
            schema: object
      "404":
        "not found"
      "405":
        "method not supported"



