openapi: 3.1.0
info:
  title: 测试项目
  description: 测试项目
  version: v1
paths:
  /jobs:
    summary: JOBService
    description: JOBService
    get:
      summary: 获取所有Jobs.
      description: 获取所有Jobs.
      extensions:
        x-grpc-endpoint: growing.graphql.example.JobService/GetJob
      parameters:
        - name: accessToken
          in: query
          allowEmptyValue: false
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: "jobname"
                  description:
                    type: string
                    description: "描述"
                  tags:
                    type: array
                    description: "标签"
                  index:
                    type: integer
                    description: "序号"
