/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.growing.progate.java-publishing-conventions")
}

dependencies {
    implementation(project(":core"))
    implementation(project(":utilities"))
    implementation(project(":grpc"))
    implementation(project(":graphql"))
    implementation(project(":restful"))
    implementation("io.vertx:vertx-web")
    implementation("io.vertx:vertx-web-client")
    implementation("org.slf4j:slf4j-api")
    implementation("com.typesafe:config")
    implementation("org.apache.commons:commons-text")
    implementation("org.apache.logging.log4j:log4j-api")
    implementation("org.apache.logging.log4j:log4j-core")
    implementation("org.apache.logging.log4j:log4j-slf4j-impl")

    implementation("com.google.dagger:dagger")
    annotationProcessor("com.google.dagger:dagger-compiler")

}
