language: java

orbs:
  - gradle

jobs:
  test:
    commands:
      - ./gradlew test
    scanner:
      classes:
        - "*/build/classes"
      exclusions:
        - "src/test/**"
        - "list/**"
        - "admin/**"
#    artifacts:
#      - kind: scalastyle
#        path: "target/scalastyle-result.xml"
#      - kind: scoverage
#        path: "target/*/scoverage-report/scoverage.xml"
#      - kind: cobertura
#        path: "target/*/coverage-report/cobertura.xml"
#  publish:
#    commands:
#      - sbt dist
#    artifacts:
#      - kind: app
#        group: cdp
#        name: growing-cdp
#        path: target/universal/growing-cdp-*.zip
