include:
  - project: 'open-source/gitlab-templates'
    ref: main
    file:
      - '/Gradle.gitlab-ci.yml'
      - '/Code-Quality.gitlab-ci.yml'
      - '/Jobs/Gradle-Publish.gitlab-ci.yml'

variables:
  GIT_FETCH_EXTRA_FLAGS: -o StrictHostKeyChecking=no --verbose --progress
  CI_DEBUG_TRACE: "true"
  GIT_HTTP_LOW_SPEED_LIMIT: 120000
  GIT_HTTP_LOW_SPEED_TIME: 60000
