image: uhub.service.ucloud.cn/growing/gradle:7.2-jdk11

stages:
  - test

test:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: "*/build/test-results/test/**/TEST-*.xml"
