include:
  - project: 'open-source/gitlab-templates'
    ref: main
    file:
      - '/Gradle.gitlab-ci.yml'
      - '/Code-Quality.gitlab-ci.yml'
      - '/Jobs/Gradle-Publish.gitlab-ci.yml'

check:
  stage: build
  extends: .only-base
  script: "./gradlew check"
  cache:
    key: "gradle-$CI_COMMIT_REF_NAME"
    policy: pull-push
    paths:
      - .gradle/wrapper
  artifacts:
    when: always
    reports:
      junit: "*/build/test-results/test/**/TEST-*.xml"
    paths:
      - "*/build/reports/jacoco/test/jacocoTestReport.xml"
      - "code-coverage-report/build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml"

code_coverage:
  image: uhub.service.ucloud.cn/growing_public/jacoco2cobertura:1.0.7
  stage: test
  extends: .only-base
  needs:
    - check
  script:
    - python /opt/cover2cover.py code-coverage-report/build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml $CI_PROJECT_DIR > build/cobertura.xml
  artifacts:
    reports:
      cobertura: build/cobertura.xml
