include:
  - project: 'open-source/gitlab-templates'
    ref: main
    file:
      - '/Gradle.gitlab-ci.yml'
      - '/Code-Quality.gitlab-ci.yml'
      - '/Jobs/Gradle-Publish.gitlab-ci.yml'


code_coverage:
  image: uhub.service.ucloud.cn/growing_public/jacoco2cobertura:1.0.7
  stage: test
  extends: .only-base
  before_script:
    - mkdir -p build
  needs:
    - check
  script:
    - python /opt/cover2cover.py code-coverage-report/build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml $CI_PROJECT_DIR > build/cobertura.xml
  artifacts:
    reports:
      cobertura: build/cobertura.xml

