/*
 * This file was generated by the Gradle 'init' task.
 */

import com.google.protobuf.gradle.*

plugins {
    idea
    id("com.google.protobuf") version "0.8.17"
    id("io.growing.progate.java-library-conventions")
}

dependencies {

    implementation(project(":grpc-client"))
    implementation("io.grpc:grpc-stub")
    implementation("io.grpc:grpc-protobuf")
    implementation("io.grpc:grpc-services")
    implementation("io.grpc:grpc-netty-shaded")
    implementation("com.google.code.gson:gson")
    implementation("com.google.protobuf:protobuf-java-util")

    if (JavaVersion.current().isJava9Compatible) {
        compileOnly("javax.annotation:javax.annotation-api:${ComponentVersions.annotationApi}")
    }
}

protobuf {

    protoc {
        artifact = if (osdetector.os == "osx") {
            "com.google.protobuf:protoc:${ComponentVersions.protobuf}:osx-x86_64"
        } else {
            "com.google.protobuf:protoc:${ComponentVersions.protobuf}"
        }
    }

    plugins {

        id("grpc") {
            artifact = if (osdetector.os == "osx") {
                "io.grpc:protoc-gen-grpc-java:${ComponentVersions.grpc}:osx-x86_64"
            } else {
                "io.grpc:protoc-gen-grpc-java:${ComponentVersions.grpc}"
            }
        }
    }

    generateProtoTasks {
        ofSourceSet("main").forEach {
            it.plugins {
                id("grpc")
            }
        }
    }
}
