/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.growing.progate.java-publishing-conventions")
}

dependencies {

    api("com.google.guava:guava")
    api("org.apache.commons:commons-lang3")
    api("com.github.ben-manes.caffeine:caffeine")

}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}
