/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.growing.gateway.java-publishing-conventions")
}

dependencies {

    api("com.google.guava:guava")
    api("org.apache.commons:commons-lang3")
    api("com.github.ben-manes.caffeine:caffeine")

}
