/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.growing.gateway.java-library-conventions")
}

dependencies {

    api("com.google.guava:guava")
    api("org.apache.commons:commons-lang3")

}
