/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.growing.progate.java-publishing-conventions")
}

dependencies {

    api(project(":api"))
    api(project(":utilities"))
    api("org.yaml:snakeyaml")
    api("org.slf4j:slf4j-api")
    api("com.typesafe:config")
    api("com.google.inject:guice")
    api("com.google.code.gson:gson")

}
