/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `maven-publish`
    id("io.growing.gateway.java-library-conventions")
}

dependencies {

    api(project(":grpc-proto"))
    api("io.grpc:grpc-services")
    implementation(project(":utilities"))
}

publishing {
    repositories {
        publications {
            create<MavenPublication>(project.name) {
                from(components["java"])
            }
        }
        maven {
            name = "growingNexus"
            val host: String = "https://nexus.growingio.cn"
            val releasesRepoUrl = uri("$host/repository/maven-releases/")
            val snapshotsRepoUrl = uri("$host/repository/maven-snapshots/")
            url = if (version.toString().endsWith("SNAPSHOT")) snapshotsRepoUrl else releasesRepoUrl
            credentials(PasswordCredentials::class)
        }
    }
}
