/*
 * This file was generated by the Gradle 'init' task.
 */


plugins {
    id("io.growing.gateway.java-library-conventions")
}

dependencies {

    api(project(":api"))
    implementation(project(":utilities"))
    implementation(project(":grpc-proto"))
//    implementation("io.vertx:vertx-grpc")
    implementation("io.grpc:grpc-stub")
    implementation("io.grpc:grpc-protobuf")
    implementation("io.grpc:grpc-services")
    implementation("io.grpc:grpc-netty-shaded")
    implementation("com.google.code.gson:gson")
    implementation("com.google.protobuf:protobuf-java-util")
    implementation("com.github.ben-manes.caffeine:caffeine")

}
