/*
 * This file was generated by the Gradle 'init' task.
 */
import com.google.protobuf.gradle.generateProtoTasks
import com.google.protobuf.gradle.ofTest
import com.google.protobuf.gradle.protobuf
import com.google.protobuf.gradle.protoc

plugins {
    id("com.google.protobuf") version "0.8.17"
    id("io.growing.progate.java-publishing-conventions")
}

dependencies {

    api(project(":core"))
    api(project(":utilities"))
    api(project(":grpc-proto"))
    api("io.grpc:grpc-stub")
    api("io.grpc:grpc-protobuf")
    api("io.grpc:grpc-services")
    api("com.google.protobuf:protobuf-java-util")
    implementation("io.grpc:grpc-netty-shaded")
    implementation("com.google.code.gson:gson")
    implementation("com.github.ben-manes.caffeine:caffeine")
    implementation("com.fasterxml.jackson.core:jackson-databind")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml")


    if (JavaVersion.current().isJava9Compatible) {
        compileOnly("javax.annotation:javax.annotation-api:${ComponentVersions.annotationApi}")
    }

}

protobuf {

    protoc {
        artifact = if (osdetector.os == "osx") {
            "com.google.protobuf:protoc:${ComponentVersions.protobuf}:osx-x86_64"
        } else {
            "com.google.protobuf:protoc:${ComponentVersions.protobuf}"
        }
    }

    generateProtoTasks {
        ofTest()
    }
}
