/*
 * This file was generated by the Gradle 'init' task.
 */
import com.google.protobuf.gradle.generateProtoTasks
import com.google.protobuf.gradle.ofTest
import com.google.protobuf.gradle.protobuf
import com.google.protobuf.gradle.protoc

plugins {
    id("com.google.protobuf") version "0.8.17"
    id("io.growing.gateway.java-library-conventions")
}

dependencies {

    api(project(":core"))
    implementation(project(":utilities"))
    implementation(project(":grpc-proto"))
//    implementation("io.vertx:vertx-grpc")
    implementation("io.grpc:grpc-stub")
    implementation("io.grpc:grpc-protobuf")
    implementation("io.grpc:grpc-services")
    implementation("io.grpc:grpc-netty-shaded")
    implementation("com.google.code.gson:gson")
    implementation("com.google.protobuf:protobuf-java-util")
    implementation("com.github.ben-manes.caffeine:caffeine")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.12.5")

    if (JavaVersion.current().isJava9Compatible) {
        compileOnly("javax.annotation:javax.annotation-api:1.3.2")
    }

}

protobuf {

    protoc {
        artifact = if (osdetector.os == "osx") {
            "com.google.protobuf:protoc:${ComponentVersions.protobuf}:osx-x86_64"
        } else {
            "com.google.protobuf:protoc:${ComponentVersions.protobuf}"
        }
    }

    generateProtoTasks {
        ofTest()
    }
}
