/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.growing.gateway.java-library-conventions")
}

dependencies {

    implementation(project(":core"))
    implementation("com.graphql-java:graphql-java")

}
