/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.growing.progate.java-library-conventions")
}

configurations {
    create("grpcLibs")
    create("grpcPlugins")
}

dependencies {

    "grpcLibs"("io.grpc:grpc-stub:${ComponentVersions.grpc}")
    "grpcLibs"("io.grpc:grpc-protobuf:${ComponentVersions.grpc}")
    "grpcLibs"("io.grpc:grpc-netty-shaded:${ComponentVersions.grpc}")
    "grpcLibs"("org.apache.tomcat:annotations-api:${ComponentVersions.tomcatAnnotationsApi}")

    "grpcPlugins"("io.grpc:protoc-gen-grpc-java:${ComponentVersions.grpc}:osx-x86_64@exe")
    "grpcPlugins"("io.grpc:protoc-gen-grpc-java:${ComponentVersions.grpc}:linux-x86_32@exe")
    "grpcPlugins"("io.grpc:protoc-gen-grpc-java:${ComponentVersions.grpc}:linux-x86_64@exe")
    "grpcPlugins"("io.grpc:protoc-gen-grpc-java:${ComponentVersions.grpc}:linux-aarch_64@exe")
    "grpcPlugins"("io.grpc:protoc-gen-grpc-java:${ComponentVersions.grpc}:windows-x86_32@exe")
    "grpcPlugins"("io.grpc:protoc-gen-grpc-java:${ComponentVersions.grpc}:windows-x86_64@exe")

}

val copyGrpcLibs by tasks.registering(Copy::class) {
    from(configurations.named("grpcLibs"))
    into("${project.buildDir}/libs")
}

val copyGrpcPlugins by tasks.registering(Copy::class) {
    from(configurations.named("grpcPlugins"))
    into("${project.buildDir}/plugins")
}
