/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.growing.progate.java-library-conventions")
}

dependencies {

    implementation(project(":utilities"))
    implementation("org.slf4j:slf4j-api")
    implementation("com.github.os72:protoc-jar")

}
