/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.growing.gateway.java-library-conventions")
}

dependencies {
    api(project(":graphql-gateway-utilities"))
    api("io.vertx:vertx-core")
    api("org.slf4j:slf4j-api")
    api("com.typesafe:config")
    api("org.apache.commons:commons-text")

}
