/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.growing.gateway.java-library-conventions")
}

dependencies {
    api(project(":graphql-gateway-api"))
    api(project(":graphql-gateway-utilities"))
    api("org.slf4j:slf4j-api")
    api("com.typesafe:config")

}
