/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.growing.gateway.java-application-conventions")
}

dependencies {
    implementation(project(":graphql-gateway-utilities"))
    implementation("io.vertx:vertx-web")
    implementation("org.slf4j:slf4j-api")
    implementation("com.typesafe:config")
    implementation("org.apache.commons:commons-text")
    implementation("org.apache.logging.log4j:log4j-api")
    implementation("org.apache.logging.log4j:log4j-core")
    implementation("org.apache.logging.log4j:log4j-slf4j-impl")

    implementation("com.graphql-java:graphql-java")

}

application {
    // Define the main class for the application.
    mainClass.set("io.growing.gateway.app.GraphQLGatewayBootstrap")
}
